import type { PlatformLocale } from "./platform-i18n";

export type PlatformCopy = typeof en;

const en = {
  langLabel: "Language",
  langSwitchTo: "Auf Deutsch ansehen",
  nav: {
    services: "Services",
    tour: "Product tour",
    how: "How it works",
    pricing: "Pricing",
    compliance: "Compliance",
    contact: "Contact",
    bookDemo: "Book a demo",
    home: "Home",
    trust: "Trust",
    privacy: "Privacy",
    terms: "Terms",
    cookies: "Cookies",
    operatorSignIn: "Operator sign in",
  },
  hero: {
    badge: "Sell. Serve. Grow.",
    pageTitle: "dishbee — Sell. Serve. Grow. | Ordering platform for independent venues",
    h1: "Everything a hospitality business needs to sell direct — website, ordering, kitchen, till and books.",
    lead: "dishbee is a complete, white-label hospitality platform for independent cafés, restaurants and food-service businesses. Your own brand, domain and menu — with direct ordering, EPOS, kitchen display, driver app, voucher schemes and financial reporting in one connected system.",
    ctaPrimary: "Get your venue live",
    ctaSecondary: "See what's included",
    imageAlt: "Café counter with EPOS till, card reader and kitchen display screen in use during service",
    imageTitle: "A live production venue",
    imageSub: "Web, app, KDS, till and drivers on one system",
    stats: [
      ["0%", "commission on your own direct orders"],
      ["1 system", "web, app, KDS, EPOS, drivers and finance"],
      ["Days", "typical time from kick-off to going live"],
    ] as [string, string][],
  },
  services: {
    eyebrow: "Modules",
    heading: "What we provide",
    lead: "Every module below is already live in production — not a roadmap. Take the whole platform or the parts you need.",
    items: [
      ["Branded website & SEO", "Fast, mobile-first marketing site with local SEO pages, blog, structured data, sitemap and social feeds — built per venue, not a template page."],
      ["Direct ordering app (PWA)", "Dine-in, collection and delivery with time slots, live menu search, allergen info, saved baskets and installable app on iOS and Android."],
      ["Kitchen Display System", "Colour-coded KDS by channel and fulfilment type, cooked/not-cooked banners, area moves, audible alerts and dual ticket printing."],
      ["EPOS & card payments", "Till app with SumUp Solo card reader, cash drawer, customer display, receipt printing and online card checkout — one ledger for every channel."],
      ["Vouchers & code schemes", "Built-in voucher issuing, gated access codes, single-use redemption, automatic email-based discounts and secure server-side promo validation."],
      ["Driver app & live tracking", "Assign or claim jobs, turn-by-turn routing, live map tracking for customers and automatic status notifications end to end."],
      ["Financials & reporting", "Sales, gross margin, food cost, expenses, supplier invoices, payment mix, settlement imports and daily P&L snapshots."],
      ["Stock & suppliers", "Inventory items, purchase receipts, waste and staff-meal tracking, low-stock alerts and cost-price control per recipe line."],
      ["House accounts & tabs", "Company tabs with credit limits, weekly billing runs, statements and MFA-protected account management."],
      ["Marketplace integrations", "Deliveroo and Just Eat orders pulled into the same KDS and reports, so every channel is visible in one place."],
      ["QR & on-site journeys", "Table and counter QR ordering, gated menus for specific groups, attendance codes and printable signage."],
      ["Security & compliance", "Role-based access, row-level database security, audit trails, GDPR-safe data handling, cookie consent and MFA for sensitive areas."],
    ] as [string, string][],
  },
  tour: {
    eyebrow: "Product tour",
    heading: "Screens from a live venue",
    lead: "Real screens from the production system running every trading day — rebranded to your venue, not a stock mockup.",
    shots: [
      ["Marketing site", "Promo banners, live opening status and prep-time estimates.", "Venue homepage with promotional carousel, live open/closed status and order call-to-action"],
      ["Menu & ordering", "Category rail, instant search, dietary filters and one-tap add.", "Menu browsing screen with category sidebar, search, dietary filters and item cards"],
      ["Order-direct funnel", "Conversion page that pulls customers off aggregator apps.", "Order-direct marketing page listing loyalty, live tracking and payment benefits"],
    ] as [string, string, string][],
    mobileAlt: "Mobile ordering app showing category chips, menu items with prices and bottom tab bar",
    mobileCaption: "Installable PWA — same system on the customer's phone.",
  },
  how: {
    eyebrow: "Onboarding",
    heading: "How it works",
    steps: [
      ["Discovery", "We map your menu, opening hours, service types, delivery radius and pricing rules."],
      ["Build & brand", "Your own deployment, colours, logo, domain and content — live in days, not months."],
      ["Hardware & payments", "Card reader, printers and drawer configured, payouts connected and tested end to end."],
      ["Go live & support", "Staff training, launch checklist, monitoring and ongoing updates from one team."],
    ] as [string, string][],
  },
  pricing: {
    eyebrow: "Pricing",
    heading: "Simple monthly plans",
    lead: "Per venue, billed monthly. Card processing is charged by your payment provider.",
    perMonth: "/month",
    popular: "Most popular",
    enquire: "Enquire",
    talkToUs: "Talk to us",
    plans: [
      {
        name: "Starter",
        blurb: "Single site getting off the marketplaces.",
        items: ["Branded website & SEO", "Direct ordering + card payments", "KDS with ticket printing", "Email support"],
      },
      {
        name: "Growth",
        blurb: "Busy venues running delivery and tabs.",
        items: ["Everything in Starter", "EPOS till, drawer & customer display", "Driver app + live tracking", "Vouchers, promos & house accounts"],
      },
      {
        name: "Enterprise",
        blurb: "Multi-site groups and bespoke workflows.",
        items: ["Everything in Growth", "Multi-site reporting & rollups", "Marketplace integrations", "Custom features & priority SLA"],
      },
    ],
  },
  trust: {
    eyebrow: "Trust",
    heading: "Built to be trusted",
    lead: "Every part of the platform follows compliance-minded defaults: secure payments, transparent data handling, audit trails and accessibility from the start.",
    items: [
      ["Encrypted & secure", "HTTPS in transit, role-based access, row-level database security and audit logs for sensitive changes."],
      ["Payment-safe", "Card payments are handled by SumUp. The platform never stores full card numbers, CVV or PIN data."],
      ["Cookie consent", "Granular consent for analytics and marketing, with strictly-necessary storage only until a choice is made."],
      ["GDPR-ready", "Data request workflows, purpose limitation and clear privacy, terms and cookie policies for every tenant."],
    ] as [string, string][],
    ctaCompliance: "Read full compliance details",
    ctaPrivacy: "Privacy policy",
  },
  contact: {
    heading: "Let's get your venue selling direct",
    lead: "Tell us about your site and we'll show you the live dishbee system, then scope your build and brand.",
    email: "Email us",
    call: "Call us",
    cardHeading: "See it in the wild",
    cardLead: "A live hospitality venue runs the full stack every trading day: online ordering, KDS, EPOS, drivers, vouchers and nightly financial reporting.",
    cardItems: [
      "Live orders across web, till and marketplaces",
      "Kitchen tickets printed automatically",
      "Daily P&L without spreadsheets",
    ],
    cardLink: "View a live venue example",
  },
  compliance: {
    heading: "Compliance & Trust",
    updated: "Last updated: 26 July 2026",
    lead: "dishbee is built for hospitality venues that need to protect customer data, prove payment security and stay accessible to every guest.",
    security: {
      heading: "Security by design",
      badges: ["HTTPS in transit", "Role-based access control", "Audit logging", "Row-level database security"],
      body: "Every tenant is deployed with its own database isolation, role-based access, and row-level security policies. Staff, drivers, kitchen and admin roles each see only the data they need. Changes to sensitive settings are logged and can be reviewed in the operator dashboard.",
    },
    privacy: {
      heading: "Privacy & GDPR",
      badges: ["Cookie consent", "Data request workflows", "Lawful-basis purpose limiting"],
      body: "We collect the minimum data needed to take, prepare and deliver an order. Card details are handled by SumUp and never stored by us. Cookie consent is required before any analytics or marketing storage loads, and customers can request data deletion or export through the venue contact. Each tenant's own privacy notice explains their specific data use.",
    },
    payments: {
      heading: "Payments",
      badges: ["SumUp card processing", "No card data stored"],
      body: "Online, till and card-reader payments are processed by SumUp, which maintains its own PCI DSS compliance programme. The platform stores only a payment reference and status, never the full card number, CVV or PIN.",
    },
    accessibility: {
      heading: "Accessibility",
      body: "The ordering interface is designed for touch, keyboard and screen-reader use, with semantic headings, ARIA labels, skip links, and contrast-checked colour schemes. We keep legacy browser compatibility in mind for older hospitality hardware and tablets.",
    },
    food: {
      heading: "Food safety & allergens",
      body: "The menu system supports allergen tagging, item-level notes, and clear customer-facing warnings. Orders print to the kitchen with the same notes that the customer sees, so staff can act on dietary requests consistently. Venue-specific food hygiene procedures remain the responsibility of the operator.",
    },
    legal: {
      heading: "Legal documents",
      body: "Each live venue publishes its own legal pages. We recommend every tenant adapts and hosts equivalent documents for their own business:",
      links: ["Privacy Policy", "Terms & Conditions", "Cookie Policy", "GDPR & Data Rights", "Complaints"],
    },
    questions: {
      heading: "Questions",
      bodyBefore: "If you need a security questionnaire, DPA or compliance review for your business, email us at ",
      bodyAfter: ".",
    },
    contactBox: "Contact us",
  },
};

const de: PlatformCopy = {
  langLabel: "Sprache",
  langSwitchTo: "View in English",
  nav: {
    services: "Leistungen",
    tour: "Produkttour",
    how: "So funktioniert's",
    pricing: "Preise",
    compliance: "Compliance",
    contact: "Kontakt",
    bookDemo: "Demo buchen",
    home: "Start",
    trust: "Vertrauen",
    privacy: "Datenschutz",
    terms: "AGB",
    cookies: "Cookies",
    operatorSignIn: "Betreiber-Login",
  },
  hero: {
    badge: "Verkaufen. Servieren. Wachsen.",
    pageTitle: "dishbee — Verkaufen. Servieren. Wachsen. | Bestellplattform für unabhängige Betriebe",
    h1: "Alles, was ein Gastronomiebetrieb braucht, um direkt zu verkaufen — Website, Bestellung, Küche, Kasse und Buchhaltung.",
    lead: "dishbee ist eine vollständige White-Label-Plattform für unabhängige Cafés, Restaurants und Food-Service-Betriebe. Eigene Marke, eigene Domain, eigene Speisekarte — mit Direktbestellung, Kassensystem, Küchendisplay, Fahrer-App, Gutscheinsystemen und Finanzauswertungen in einem verbundenen System.",
    ctaPrimary: "Betrieb live schalten",
    ctaSecondary: "Alle Leistungen ansehen",
    imageAlt: "Café-Theke mit Kassensystem, Kartenleser und Küchendisplay im laufenden Betrieb",
    imageTitle: "Ein Betrieb im Live-Einsatz",
    imageSub: "Web, App, Küchendisplay, Kasse und Fahrer in einem System",
    stats: [
      ["0 %", "Provision auf Ihre eigenen Direktbestellungen"],
      ["1 System", "Web, App, Küchendisplay, Kasse, Fahrer und Finanzen"],
      ["Tage", "typische Zeit vom Start bis zum Go-live"],
    ],
  },
  services: {
    eyebrow: "Module",
    heading: "Unsere Leistungen",
    lead: "Jedes Modul ist bereits im Live-Betrieb — keine Roadmap. Nehmen Sie die ganze Plattform oder nur die Teile, die Sie brauchen.",
    items: [
      ["Website mit eigener Marke & SEO", "Schnelle, mobil-optimierte Website mit lokalen SEO-Seiten, Blog, strukturierten Daten, Sitemap und Social-Feeds — individuell pro Betrieb, keine Vorlagenseite."],
      ["Direktbestell-App (PWA)", "Vor Ort, Abholung und Lieferung mit Zeitfenstern, Live-Suche, Allergenangaben, gespeicherten Warenkörben und installierbarer App für iOS und Android."],
      ["Küchendisplay-System", "Farbcodiertes Küchendisplay nach Kanal und Bestellart, Banner für zubereitet/offen, Bereichswechsel, akustische Signale und doppelter Bonausdruck."],
      ["Kassensystem & Kartenzahlung", "Kassen-App mit SumUp-Solo-Kartenleser, Kassenlade, Kundendisplay, Belegdruck und Online-Kartenzahlung — ein Buchungsjournal für alle Kanäle."],
      ["Gutscheine & Code-Systeme", "Gutscheinausgabe, geschützte Zugangscodes, Einmal-Einlösung, automatische E-Mail-basierte Rabatte und sichere serverseitige Aktionscode-Prüfung."],
      ["Fahrer-App & Live-Tracking", "Aufträge zuweisen oder annehmen, Navigation, Live-Karte für Kundinnen und Kunden sowie automatische Statusbenachrichtigungen."],
      ["Finanzen & Auswertungen", "Umsatz, Rohertrag, Wareneinsatz, Ausgaben, Lieferantenrechnungen, Zahlungsmix, Abrechnungsimporte und tägliche Ergebnisberichte."],
      ["Warenwirtschaft & Lieferanten", "Lagerartikel, Wareneingänge, Verlust- und Personalessen-Erfassung, Mindestbestandswarnungen und Einstandspreise je Rezeptposition."],
      ["Kundenkonten & Deckel", "Firmenkonten mit Kreditlimits, wöchentliche Abrechnungsläufe, Kontoauszüge und MFA-geschützte Kontoverwaltung."],
      ["Marktplatz-Anbindungen", "Bestellungen von Lieferplattformen laufen in dasselbe Küchendisplay und dieselben Auswertungen — alle Kanäle an einem Ort."],
      ["QR & Bestellung vor Ort", "QR-Bestellung am Tisch und am Tresen, geschützte Speisekarten für bestimmte Gruppen, Anwesenheitscodes und druckbare Beschilderung."],
      ["Sicherheit & Compliance", "Rollenbasierte Zugriffe, Row-Level-Sicherheit in der Datenbank, Audit-Protokolle, DSGVO-konforme Datenverarbeitung, Cookie-Einwilligung und MFA für sensible Bereiche."],
    ],
  },
  tour: {
    eyebrow: "Produkttour",
    heading: "Ansichten aus dem Live-Betrieb",
    lead: "Echte Screens aus dem produktiven System im täglichen Einsatz — im Design Ihres Betriebs, kein Stock-Mockup.",
    shots: [
      ["Website", "Aktionsbanner, Live-Öffnungsstatus und Zubereitungszeiten.", "Startseite mit Aktionskarussell, Live-Öffnungsstatus und Bestell-Button"],
      ["Speisekarte & Bestellung", "Kategorieleiste, Sofortsuche, Ernährungsfilter und Hinzufügen mit einem Tipp.", "Speisekarte mit Kategorieleiste, Suche, Ernährungsfiltern und Artikelkarten"],
      ["Direktbestell-Funnel", "Landingpage, die Gäste von Lieferportalen zu Ihnen holt.", "Marketingseite für Direktbestellungen mit Treue-, Tracking- und Zahlungsvorteilen"],
    ],
    mobileAlt: "Mobile Bestell-App mit Kategorie-Chips, Artikeln mit Preisen und unterer Navigationsleiste",
    mobileCaption: "Installierbare PWA — dasselbe System auf dem Handy Ihrer Gäste.",
  },
  how: {
    eyebrow: "Einführung",
    heading: "So funktioniert's",
    steps: [
      ["Analyse", "Wir erfassen Speisekarte, Öffnungszeiten, Servicearten, Lieferradius und Preisregeln."],
      ["Aufbau & Branding", "Eigene Installation, Farben, Logo, Domain und Inhalte — live in Tagen, nicht Monaten."],
      ["Hardware & Zahlungen", "Kartenleser, Drucker und Kassenlade eingerichtet, Auszahlungen verbunden und vollständig getestet."],
      ["Go-live & Support", "Mitarbeiterschulung, Launch-Checkliste, Monitoring und laufende Updates aus einer Hand."],
    ],
  },
  pricing: {
    eyebrow: "Preise",
    heading: "Einfache Monatspakete",
    lead: "Pro Betrieb, monatliche Abrechnung. Die Kartengebühren rechnet Ihr Zahlungsdienstleister ab.",
    perMonth: "/Monat",
    popular: "Am beliebtesten",
    enquire: "Anfragen",
    talkToUs: "Auf Anfrage",
    plans: [
      {
        name: "Starter",
        blurb: "Ein Standort, der weg von den Lieferportalen will.",
        items: ["Website mit eigener Marke & SEO", "Direktbestellung + Kartenzahlung", "Küchendisplay mit Bonausdruck", "E-Mail-Support"],
      },
      {
        name: "Growth",
        blurb: "Betriebe mit viel Lieferung und Kundenkonten.",
        items: ["Alles aus Starter", "Kasse, Kassenlade & Kundendisplay", "Fahrer-App + Live-Tracking", "Gutscheine, Aktionen & Kundenkonten"],
      },
      {
        name: "Enterprise",
        blurb: "Mehrere Standorte und individuelle Abläufe.",
        items: ["Alles aus Growth", "Standortübergreifende Auswertungen", "Marktplatz-Anbindungen", "Individuelle Funktionen & Priority-SLA"],
      },
    ],
  },
  trust: {
    eyebrow: "Vertrauen",
    heading: "Auf Vertrauen gebaut",
    lead: "Jeder Teil der Plattform folgt compliance-orientierten Standards: sichere Zahlungen, transparente Datenverarbeitung, Audit-Protokolle und Barrierefreiheit von Anfang an.",
    items: [
      ["Verschlüsselt & sicher", "HTTPS bei der Übertragung, rollenbasierte Zugriffe, Row-Level-Sicherheit und Audit-Protokolle für sensible Änderungen."],
      ["Zahlungssicher", "Kartenzahlungen werden von SumUp abgewickelt. Die Plattform speichert nie vollständige Kartennummern, CVV oder PIN."],
      ["Cookie-Einwilligung", "Granulare Einwilligung für Analyse und Marketing; bis zur Entscheidung werden nur notwendige Daten gespeichert."],
      ["DSGVO-bereit", "Prozesse für Auskunfts- und Löschanfragen, Zweckbindung sowie klare Datenschutz-, AGB- und Cookie-Richtlinien für jeden Mandanten."],
    ],
    ctaCompliance: "Vollständige Compliance-Details lesen",
    ctaPrivacy: "Datenschutzerklärung",
  },
  contact: {
    heading: "Bringen wir Ihren Betrieb zum Direktverkauf",
    lead: "Erzählen Sie uns von Ihrem Betrieb — wir zeigen Ihnen das dishbee-System live und planen dann Aufbau und Branding.",
    email: "E-Mail schreiben",
    call: "Anrufen",
    cardHeading: "Im echten Einsatz",
    cardLead: "Ein Gastronomiebetrieb nutzt täglich den kompletten Stack: Online-Bestellung, Küchendisplay, Kasse, Fahrer, Gutscheine und nächtliche Finanzauswertung.",
    cardItems: [
      "Live-Bestellungen aus Web, Kasse und Lieferportalen",
      "Küchenbons werden automatisch gedruckt",
      "Tägliche Ergebnisrechnung ohne Tabellen",
    ],
    cardLink: "Live-Beispiel ansehen",
  },
  compliance: {
    heading: "Compliance & Vertrauen",
    updated: "Zuletzt aktualisiert: 26. Juli 2026",
    lead: "dishbee ist für Gastronomiebetriebe gebaut, die Kundendaten schützen, Zahlungssicherheit nachweisen und für alle Gäste zugänglich bleiben müssen.",
    security: {
      heading: "Sicherheit von Grund auf",
      badges: ["HTTPS bei der Übertragung", "Rollenbasierte Zugriffskontrolle", "Audit-Protokollierung", "Row-Level-Sicherheit"],
      body: "Jeder Mandant erhält eine eigene Datenbankisolierung, rollenbasierte Zugriffe und Row-Level-Security-Richtlinien. Service, Fahrer, Küche und Verwaltung sehen jeweils nur die Daten, die sie benötigen. Änderungen an sensiblen Einstellungen werden protokolliert und sind im Betreiber-Dashboard einsehbar.",
    },
    privacy: {
      heading: "Datenschutz & DSGVO",
      badges: ["Cookie-Einwilligung", "Prozesse für Datenanfragen", "Zweckbindung nach Rechtsgrundlage"],
      body: "Wir erheben nur die Daten, die zur Annahme, Zubereitung und Lieferung einer Bestellung nötig sind. Kartendaten werden von SumUp verarbeitet und nie von uns gespeichert. Vor dem Laden von Analyse- oder Marketing-Speicher ist eine Cookie-Einwilligung erforderlich; Gäste können Löschung oder Export über den Betrieb anfordern. Die Datenschutzerklärung jedes Mandanten erläutert die konkrete Datennutzung.",
    },
    payments: {
      heading: "Zahlungen",
      badges: ["Kartenzahlung über SumUp", "Keine Kartendaten gespeichert"],
      body: "Online-, Kassen- und Kartenleserzahlungen werden von SumUp verarbeitet, das ein eigenes PCI-DSS-Compliance-Programm unterhält. Die Plattform speichert nur Zahlungsreferenz und Status, nie die vollständige Kartennummer, CVV oder PIN.",
    },
    accessibility: {
      heading: "Barrierefreiheit",
      body: "Die Bestelloberfläche ist für Touch, Tastatur und Screenreader ausgelegt — mit semantischen Überschriften, ARIA-Labels, Sprunglinks und kontrastgeprüften Farbschemata. Ältere Gastro-Hardware und Tablets werden bewusst unterstützt.",
    },
    food: {
      heading: "Lebensmittelsicherheit & Allergene",
      body: "Das Speisekartensystem unterstützt Allergenkennzeichnung, Hinweise je Artikel und deutliche Warnhinweise für Gäste. Bestellungen werden mit denselben Hinweisen in der Küche gedruckt, die der Gast sieht, sodass Ernährungswünsche konsistent umgesetzt werden. Die betrieblichen Hygienevorgaben verantwortet der Betreiber.",
    },
    legal: {
      heading: "Rechtliche Dokumente",
      body: "Jeder Betrieb veröffentlicht eigene Rechtstexte. Wir empfehlen jedem Mandanten, entsprechende Dokumente für das eigene Unternehmen anzupassen und bereitzustellen:",
      links: ["Datenschutzerklärung", "Allgemeine Geschäftsbedingungen", "Cookie-Richtlinie", "DSGVO & Betroffenenrechte", "Beschwerden"],
    },
    questions: {
      heading: "Fragen",
      bodyBefore: "Wenn Sie einen Sicherheitsfragebogen, einen AV-Vertrag oder eine Compliance-Prüfung benötigen, schreiben Sie uns an ",
      bodyAfter: ".",
    },
    contactBox: "Kontakt",
  },
};

export const platformCopy: Record<PlatformLocale, PlatformCopy> = { en, de };
