INSERT INTO public.blog_posts (slug, title, excerpt, cover_url, body_md, tags, author, published, published_at) VALUES
('italian-coffee-in-st-albans',
 'Why our Italian coffee tastes different',
 'A proper Italian roast, pulled fresh on the counter at St Albans Crown Court. Here is what goes into every cup.',
 '/blog/italian-coffee.jpg',
 E'## A proper Italian roast\n\nEvery cup at Cafe 1 starts with a genuine Italian espresso blend, ground fresh through the morning and pulled to order. No pre-ground shortcuts, no burnt bitterness.\n\n### What we serve\n\n- **Espresso and double espresso** — short, sweet, and thick with crema\n- **Flat white and cappuccino** — properly textured milk, not froth\n- **Latte and mocha** — smooth and balanced\n- **Filter coffee** — for when you need a big cup at your desk\n\n### Grab it on the way in\n\nOrder ahead on the website and your coffee is ready when you arrive. Delivery is free within half a mile, minimum £10 order, and we are open Monday to Friday, 8:30am to 5pm.\n\nGot a favourite order? Ask about our Coffee & Tea Card — every eleventh drink is on us.',
 ARRAY['coffee','cafe1'], 'Cafe 1', true, now() - interval '2 days'),
('halal-breakfast-st-albans',
 'Halal breakfast, served fresh every morning',
 'Everything we cook is 100% halal. Here is what is on the breakfast counter from 8:30am.',
 '/blog/halal-breakfast.jpg',
 E'## 100% halal, every day\n\nAll food at Cafe 1 is fully halal — no exceptions, no separate menu. Whether you are grabbing a breakfast bap on the way in or a full plate before a long day, it is prepared fresh on site.\n\n### On the breakfast menu\n\n- Breakfast baps and rolls\n- Full breakfast plates with eggs, beans and toast\n- Toasties and paninis\n- Jacket potatoes with your choice of fillings\n\n### Make it a meal\n\nAdd a drink and a side to most hot items for just **£2** at checkout.\n\nBreakfast runs from opening at 8:30am. Order ahead for dine in, pickup or delivery and skip the queue.',
 ARRAY['food','halal','breakfast'], 'Cafe 1', true, now() - interval '5 days'),
('office-delivery-crown-court',
 'Free delivery to offices within half a mile',
 'We deliver hot food and coffee straight to nearby offices and chambers — free, within half a mile of AL1 3JW.',
 '/blog/office-delivery.jpg',
 E'## Lunch without leaving the desk\n\nCafe 1 sits inside St Albans Crown Court, AL1 3JW, and we deliver to offices, chambers and businesses within **half a mile** — completely free on orders over £10.\n\n### How it works\n\n1. Build your order on the website and choose **Delivery**\n2. Enter your postcode — we check instantly whether you are inside our area\n3. Pick **ASAP** or a time slot that suits your meeting\n4. Pay by card, Apple Pay or Google Pay\n\nTypical prep time is around 20 minutes, with delivery orders taken up to 4:30pm.\n\n### Outside the area?\n\nYou can still order for **pickup** or **dine in** — just choose that option at the start and the rest works the same.\n\n### Regular orders\n\nBusinesses who order often can run a house account (a tab) and settle weekly. Ask us in store to get set up.',
 ARRAY['delivery','offices'], 'Cafe 1', true, now() - interval '1 day')
ON CONFLICT (slug) DO NOTHING;